CICD

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -56,16 +56,23 @@ jobs:
     steps:
       - name: Set target IP
         run: |
+          # Fail on errors being ignored
+          set +e  # Disable immediate exit on errors
+          
           # Check health status on 8080 port
-          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.TECHMAIL_SERVER_IP }}:8080/actuator/health")
+          STATUS=$(curl -o /dev/null -w "%{http_code}" -s "http://${{ secrets.TECHMAIL_SERVER_IP }}:8080/actuator/health")
           echo "Health check status on 8080: $STATUS"
           
-          if [ $STATUS = 200 ]; then
+          if [ "$STATUS" -eq 200 ]; then
             CURRENT_PORT=BLUE
           else
+            echo "Health check failed or unable to connect. Status code: $STATUS"
             CURRENT_PORT=GREEN
           fi
           
+          # Enable error exit handling again
+          set -e  # Re-enable immediate exit on errors
+
           echo "CURRENT_PORT=$CURRENT_PORT" >> $GITHUB_ENV
 
           # Set environment variables based on CURRENT_PORT
